CREATE TABLE customers (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) UNIQUE,
    join_date DATE DEFAULT TRUNC(SYSDATE)
);

CREATE TABLE products (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR2(100) NOT NULL,
    category VARCHAR2(50) NOT NULL,
    price NUMBER(10,2) CHECK (price > 0)
);

CREATE TABLE orders (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER REFERENCES customers(customer_id),
    order_date TIMESTAMP NOT NULL,
    status VARCHAR2(20) NOT NULL
);

CREATE TABLE order_items (
    order_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER REFERENCES orders(order_id),
    product_id NUMBER REFERENCES products(product_id),
    quantity NUMBER CHECK (quantity > 0),
    unit_price NUMBER(10,2) NOT NULL
);


-- Customers
INSERT INTO customers (customer_id, first_name, last_name, email, join_date) 
VALUES (1, 'Alex', 'Miller', 'alex.m@email.com', TO_DATE('2023-01-15', 'YYYY-MM-DD'));
INSERT INTO customers (customer_id, first_name, last_name, email, join_date) 
VALUES (2, 'Sarah', 'Jenkins', 's.jenkins@email.com', TO_DATE('2023-02-20', 'YYYY-MM-DD'));
INSERT INTO customers (customer_id, first_name, last_name, email, join_date) 
VALUES (3, 'Mike', 'Chen', NULL, TO_DATE('2023-03-05', 'YYYY-MM-DD'));
INSERT INTO customers (customer_id, first_name, last_name, email, join_date) 
VALUES (4, 'Emma', 'Watson', 'emma.w@email.com', TO_DATE('2023-03-10', 'YYYY-MM-DD'));
INSERT INTO customers (customer_id, first_name, last_name, email, join_date) 
VALUES (5, 'Alex', 'Miller', 'alex.miller2@email.com', TO_DATE('2023-04-01', 'YYYY-MM-DD'));

-- Products
INSERT INTO products (product_id, product_name, category, price) 
VALUES (1, 'Classic White Tee', 'Tops', 25.00);
INSERT INTO products (product_id, product_name, category, price) 
VALUES (2, 'Vintage Denim Jacket', 'Outerwear', 85.00);
INSERT INTO products (product_id, product_name, category, price) 
VALUES (3, 'Slim Fit Jeans', 'Bottoms', 60.00);
INSERT INTO products (product_id, product_name, category, price) 
VALUES (4, 'Cotton Beanie', 'Accessories', 15.00);
INSERT INTO products (product_id, product_name, category, price) 
VALUES (5, 'Graphic Hoodie', 'Tops', 45.00);
INSERT INTO products (product_id, product_name, category, price) 
VALUES (6, 'Leather Belt', 'Accessories', 30.00);

-- Orders
INSERT INTO orders (order_id, customer_id, order_date, status) 
VALUES (1, 1, TO_TIMESTAMP('2023-02-10 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) 
VALUES (2, 2, TO_TIMESTAMP('2023-02-25 09:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) 
VALUES (3, 1, TO_TIMESTAMP('2023-03-01 18:45:00', 'YYYY-MM-DD HH24:MI:SS'), 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) 
VALUES (4, 3, TO_TIMESTAMP('2023-03-10 11:20:00', 'YYYY-MM-DD HH24:MI:SS'), 'Cancelled');
INSERT INTO orders (order_id, customer_id, order_date, status) 
VALUES (5, 4, TO_TIMESTAMP('2023-04-05 16:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) 
VALUES (6, 2, TO_TIMESTAMP('2023-04-12 13:10:00', 'YYYY-MM-DD HH24:MI:SS'), 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) 
VALUES (7, 5, TO_TIMESTAMP('2023-04-20 10:05:00', 'YYYY-MM-DD HH24:MI:SS'), 'Pending');

-- Order Items
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) 
VALUES (1, 1, 1, 2, 25.00);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) 
VALUES (2, 1, 4, 1, 15.00);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) 
VALUES (3, 2, 2, 1, 85.00);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) 
VALUES (4, 3, 3, 1, 60.00);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) 
VALUES (5, 3, 1, 1, 25.00);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) 
VALUES (6, 4, 5, 2, 45.00);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) 
VALUES (7, 5, 6, 1, 30.00);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) 
VALUES (8, 5, 4, 2, 15.00);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) 
VALUES (9, 6, 2, 1, 85.00);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) 
VALUES (10, 6, 3, 2, 60.00);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) 
VALUES (11, 7, 1, 3, 25.00);

COMMIT;
