
/*Which customers have not provided an email address during registration so that customer
service can flag them for profile updates?*/
select customer_id,first_name,last_name, join_date from customers 
where email is null;


/*Generate a customer directory report where any missing email address displays as 
'No Email Provided' instead of a blank or NULL value.*/
select first_name,last_name,
coalesce(email,'NO EMAIL PROVIDED') as contact_email
from customers;


/*What is the total revenue generated by each product category across all order items?
Rank categories from highest to lowest.*/
select p.category, sum(oi.quantity * oi.unit_price) AS total_revenue
from products p
join order_items oi ON p.product_id = oi.product_id
group by category 
order by total_revenue desc;



/*What is our monthly revenue trend over time? Include only 'Completed' orders so 
finance does not overestimate cash flow.*/
select trunc(o.order_date,'MM') as order_month,
sum(oi.quantity * oi.unit_price) as monthly_revenue
from orders o 
join order_items oi on o.order_id = oi.order_id 
where o.status = 'Completed'
group by trunc(o.order_date,'MM')
order by order_month asc;


/*Classify each order into 'High Value' (order total > $100) or 'Standard' (order total <= $100). 
How many orders fall into each tier?*/
with order_summaries as (
    select order_id ,sum(quantity * unit_price) as order_total
    from ORDER_ITEMS
    group by order_id
)
select 
    case 
        when order_total > 100 then 'HIGH VALUE'
        else 'STANDARD'
    end as order_tier,
    count(order_id ) as total_orders
from order_summaries
group by 
    case 
        when order_total > 100 then 'HIGH VALUE' 
        else 'STANDARD'
    end ;   